CC      = avr-gcc
WARN    = -Wall -Wextra
LDFLAGS = -lm
CFLAGS  = -Os -std=gnu99 -g -ggdb $(WARN)

BASE_SOURCES = io.c \
               platforms.c \
               usb.c \
               usb_config.c \
               usb_hardware.c \
               crc.c \
               rawhid.c \
               rawhid_protocol.c \
               hid.c \
               atmel_bootloader.c \
               matrix.c \
	       leds.c \
	       timer.c \
               layout.c

TARGETS = gh60 gh60b # ghpad

# Target: GH60B
OPTS_gh60b    = -mmcu=atmega32u4
SOURCES_gh60b = main_gh60.c
RESULT_gh60b  = ukbdc_gh60_revB-0.2

# Target: GH60
OPTS_gh60    = -mmcu=atmega32u4
SOURCES_gh60 = main_gh60.c
RESULT_gh60  = ukbdc_gh60-0.2_rc2

# Target: GHPad
OPTS_ghpad    = -mmcu=atmega32u2
SOURCES_ghpad = main_ghpad.c
RESULT_ghpad  = ukbdc_ghpad-0.2_rc2
